### ISSUE TITLE
Pod doesn't start: database.boltdb: permission denied

### ISSUE THREAD

**Issue by monique77** [cloudhippie/charts#219]
Hello, Guys

I would like your support please. I'm trying to install ansible semaphore 9.5.0, but it not seing possible. Bellow has a error in my pod

Versions
kubernetes v1.30.1
ansible-semaphore-9.5.0	2.10
Helm v3.15.1

My pv and pvcs
PV
mariadb-second-task-pv-volume   10Gi       RWO            Retain           Bound    default/mariadb-ansible-semaphore-boltdb    local-storage   <unset>                          33m
mariadb-task-pv-volume          10Gi       RWO            Retain           Bound    default/mariadb-ansible-semaphore-workdir   local-storage   <unset>                          34m
second-task-pv-volume           10Gi       RWO            Retain           Bound    default/my-ansible-semaphore-boltdb         local-storage   <unset>                          152m
task-pv-volume                  10Gi       RWO            Retain           Bound    default/my-ansible-semaphore-workdir        local-storage   <unset>                          152m

PVC
mariadb-ansible-semaphore-boltdb    Bound    mariadb-second-task-pv-volume   10Gi       RWO            local-storage   <unset>                 25m
mariadb-ansible-semaphore-workdir   Bound    mariadb-task-pv-volume          10Gi       RWO            local-storage   <unset>                 25m
my-ansible-semaphore-boltdb         Bound    second-task-pv-volume           10Gi       RWO            local-storage   <unset>                 133m
my-ansible-semaphore-workdir        Bound    task-pv-volume                  10Gi       RWO            local-storage   <unset>              

I don't know why it is trying to use boltdb, I installed Mariadb by chart.yaml and values.yaml. In this installation I chose mariadb.

I will appreciate your help.
Tks so much

My pod  ansible-semaphore  and  mariadb-ansible-semaphore is the same error

e-6dc99d8fc8-g49zc -n default
No additional system dependencies to install
No additional python dependencies to install
Starting semaphore server
Loading config
Validating config
panic: open /var/lib/semaphore/database.boltdb: permission denied
goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0xc0001fe090, {0xc65a96, 0x4})
	/go/src/semaphore/db/bolt/BoltDb.go:111 +0x35c
github.com/ansible-semaphore/semaphore/cli/cmd.createStore({0xc65a96, 0x4})
	/go/src/semaphore/cli/cmd/root.go:103 +0x5a
github.com/ansible-semaphore/semaphore/cli/cmd.runService()
	/go/src/semaphore/cli/cmd/root.go:44 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.init.func6(0xc000161100?, {0xc65ac2?, 0x4?, 0xc65ac6?})
	/go/src/semaphore/cli/cmd/server.go:18 +0xf
github.com/spf13/cobra.(*Command).execute(0x1d44c80, {0xc000159c80, 0x2, 0x2})
	/go/src/semaphore/vendor/github.com/spf13/cobra/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x1d44100)
	/go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1039
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
	/go/src/semaphore/cli/cmd/root.go:37 +0x54
main.main()
	/go/src/semaphore/cli/main.go:8 +0xf

**Comment by tboerger** [comment]
Please share the values.yml you are using

**Comment by monique77** [comment]
@tboerger Thomas tks for your message.

My values has only this:

```
mariadb:
  # -- Enable mariadb dependency
  enabled: true

  # -- Override fullname of mariadb dependency
  fullnameOverride: mariadb

  # -- Architecture for mariadb
  architecture: standalone

  auth:
    # -- Database created for semaphore
    database: semaphore

    # -- Username for semaphore database
    username: semaphore

    # -- Password for semaphore database
    password: xxxxxxxxx

  serviceAccount:
    # -- Create service account for mariadb
    create: true

  metrics:
    # -- Enable metrics for mariadb
    enabled: true

    serviceMonitor:
      # -- Enable service monitor for mariadb
      enabled: false
```
