### ISSUE TITLE
Initial admin

### ISSUE THREAD

**Issue by seboudry** [cloudhippie/charts#255]
Hi!

Failed to create the very first admin just after semaphore deployed (and with OIDC configured).

Is the chart already help with that?

Otherwise, I tried by following official documentation https://docs.semaphoreui.com/administration-guide/configuration#interactive-setup.

But I think the `semaphore setup` step isn't necessary.
And when continue with admin creation, I got this error when running inside semaphore pod:

```
semaphore-cfb98c56-rglnv:~$ semaphore user add --config /etc/semaphore/config.json --admin --login admin --email=admin@example.com --name Admin --password=12345
Loading config
Validating config
panic: timeout

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).openDbFile(0xc0001ea0c0)
	/go/src/semaphore/db/bolt/BoltDb.go:92 +0x1ab
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0xc0001ea0c0, {0x0, 0x0})
	/go/src/semaphore/db/bolt/BoltDb.go:121 +0x33
github.com/ansible-semaphore/semaphore/cli/cmd.createStore({0x0, 0x0})
	/go/src/semaphore/cli/cmd/root.go:103 +0x5a
github.com/ansible-semaphore/semaphore/cli/cmd.init.func9(0xc0000d3400?, {0xc74890?, 0x4?, 0xc74894?})
	/go/src/semaphore/cli/cmd/user_add.go:49 +0x205
github.com/spf13/cobra.(*Command).execute(0x1de16e0, {0xc0000b22d0, 0x9, 0x9})
	/go/src/semaphore/vendor/github.com/spf13/cobra/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x1de02c0)
	/go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1039
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
	/go/src/semaphore/cli/cmd/root.go:37 +0x54
main.main()
	/go/src/semaphore/cli/main.go:8 +0xf
```

Here's my Helm values using `10.0.7` chart version:
```yaml
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/tls-acme: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
      className: nginx
      enabled: true
      hosts:
        - host: semaphore.mycompany.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - semaphore.mycompany.com
          secretName: semaphore-certs
    oidc:
      enable: true
      providers:
        keycloak:
          display_name: QuickSign SSO
          provider_url: https://sso.mycompany.com/auth/realms/master
          redirect_url: https://semaphore.mycompany.com/api/auth/oidc/keycloak/redirect
          client_id: semaphore
          client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          username_claim: preferred_username
          name_claim: name
          email_claim: email
    database:
      type: bolt
```
