### ISSUE TITLE
extraSecretMounts for oidc secrets

### ISSUE THREAD

**Issue by plcnk** [cloudhippie/charts#292]
Hello!

It seems we can only use plain text `client_id` and `client_secret` for oidc configuration in the Semaphore chart at the moment.
It would be nice to have extra secret mounts to be able to use the `client_id_file` and `client_secret_file` variables.

For example:
```yaml
extraSecretMounts:
  - name: oidc-secret-mount
    secretName: oidc-secret
    defaultMode: 0440
    mountPath: /etc/secrets/oidc
    readOnly: true

oidc:
  enable: true
  providers:
    keycloak:
      display_name: Keycloak
      client_id_file: "/etc/secrets/oidc/client_id"
      client_secret_file: "/etc/secrets/oidc/client_secret"
```
